- name: influxdb-setup
  k8s:
    state: present
    definition: "{{ lookup('template', 'serverless/influxdb.yaml') }}"

- name: kafka-to-influxdb
  k8s:
    state: present
    definition: "{{ lookup('template', 'serverless/kafka-to-influxdb.yaml') }}"

- name: grafana
  k8s:
    state: present
    definition: "{{ lookup('template', 'serverless/grafana.yaml') }}"

- name: reviews-simulator
  k8s:
    state: present
    definition: "{{ lookup('template', 'serverless/reviews-simulator.yaml') }}"
