---

- name: "Create namespaces"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_namespaces:
      - name: "{{ ocp4_workload_cloud_architecture_workshop_module_rhsi_db_namespace_prefix }}-user"
        managedByArgo: ""
  retries: 10
  delay: 30

- name: "Give users access to projects"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'rolebinding.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_bindings:
      - namespace: "{{ ocp4_workload_cloud_architecture_workshop_module_rhsi_db_namespace_prefix }}-user"
        role: "admin"
  retries: 10
  delay: 30

- name: Deploy ArgoCD application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'globex-rhsi-application.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_module_rhsi_namespace: "{{ ocp4_workload_cloud_architecture_workshop_module_rhsi_db_namespace_prefix }}-user"

- name: Wait until ArgoCD application is deployed
  kubernetes.core.k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: "{{ ocp4_workload_cloud_architecture_workshop_module_rhsi_argo_application_name }}-user1"
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_module_rhsi_argo_application_namespace }}"
  register: r_rhsi_application
  until:
    - r_rhsi_application.resources[0].status.sync.status is defined
    - r_rhsi_application.resources[0].status.sync.status == "Synced"
    - r_rhsi_application.resources[0].status.health.status is defined
    - r_rhsi_application.resources[0].status.health.status == "Healthy"
  retries: 20
  delay: 30

- name: Run rhsi cli commands (1)
  ansible.builtin.command:
    argv:
      - skupper
      - init
      - -n
      - "{{ ocp4_workload_cloud_architecture_workshop_namespace_prefix }}-user1"
      - --enable-console
      - --enable-flow-collector
      - --console-auth
      - unsecured

- name: Run rhsi cli commands (2)
  ansible.builtin.command:
    argv:
      - skupper
      - init
      - -n
      - "{{ ocp4_workload_cloud_architecture_workshop_module_rhsi_db_namespace_prefix }}-user1"

- name: Run rhsi cli commands (3)
  ansible.builtin.command:
    argv:
      - skupper
      - token
      - create
      - -n
      - "{{ ocp4_workload_cloud_architecture_workshop_namespace_prefix }}-user1"
      - /tmp/skupper.token
  ignore_errors: true

- name: Run rhsi cli commands (4)
  ansible.builtin.command:
    argv:
      - skupper
      - link
      - create
      - -n
      - "{{ ocp4_workload_cloud_architecture_workshop_module_rhsi_db_namespace_prefix }}-user1"
      - /tmp/skupper.token
  ignore_errors: true

- name: Run rhsi cli commands (5)
  ansible.builtin.command:
    argv:
      - skupper
      - expose
      - deployment/globex-db
      - --port=5432
      - -n
      - "{{ ocp4_workload_cloud_architecture_workshop_module_rhsi_db_namespace_prefix }}-user1"
