---


- name: Remove Serverless Module
  ansible.builtin.include_tasks: remove_module_globex_serverless.yml

- name: Remove Globex application
  ansible.builtin.include_tasks: remove_workshop.yml

- name: Remove RHBK
  ansible.builtin.include_tasks: remove_rhbk.yml

- name: Remove Namespaces
  ansible.builtin.include_tasks: remove_namespaces.yml
